# -*- coding: utf-8 -*-
"""Embedded-title,transcript

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bHC661Ei74nnU7-UqdvZOja0k41fYjm
"""

pip install openai pandas

from google.colab import files
uploaded = files.upload()  # ⬅️ Choose your 'master_dataset_updated.csv' when prompted

import pandas as pd

# Make sure the name matches exactly your file name after upload
df = pd.read_csv("master_dataset_updated.csv")

# Check if loaded properly
print("✅ File loaded successfully — total rows:", len(df))
df.head(2)

# Install dependencies (run once)
# pip install pandas sentence-transformers

import pandas as pd
from sentence_transformers import SentenceTransformer

# Load CSV
df = pd.read_csv("master_dataset_updated.csv")  # your CSV file
df['combined_text'] = df['title'].astype(str) + " " + df['transcript'].astype(str)

# Load a free open-source embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')  # lightweight and good for general embeddings

# Generate embeddings
embeddings = model.encode(df['combined_text'].tolist(), show_progress_bar=True)

# Convert embeddings to list format for CSV
df['embedding'] = embeddings.tolist()

# Save to new CSV
df.to_csv("master_dataset_with_embeddings.csv", index=False)

print("Embeddings generated and saved successfully!")

# Save to CSV
df.to_csv("master_dataset_with_embeddings.csv", index=False)
print("Saved embeddings to CSV successfully!")

from google.colab import files

# Save CSV (you already did this)
df.to_csv("master_dataset_with_embeddings.csv", index=False)

# Download the file
files.download("master_dataset_with_embeddings.csv")

